# SPDX-License-Identifier: LGPL-2.1-or-later

[Config]
MinimumVersion=26~devel

[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64
Mirror=https://dl.fedoraproject.org/pub/fedora

[Build]
ToolsTree=default
ToolsTreeMirror=https://download.opensuse.org
ToolsTreeProfiles=misc,runtime
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=uki,partitions
Format=disk
ImageId=ParticleOS-Webserver
ManifestFormat=json
Output=%i_%v_%a

[Content]
SELinuxRelabel=yes
WithDocs=no
WithRecommends=no
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=1
        enforcing=1
        selinux=1
        systemd.verity_usr_options=root-hash-signature=auto
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=absent:=ignore
        systemd.image_filter=usr=ParticleOS-Webserver_*:usr-verity=ParticleOS-Webserver_*:usr-verity-sig=ParticleOS-Webserver_*:root=ParticleOS-Webserver-*:swap=ParticleOS-Webserver-*
        ipe.enforce=1
        slab_nomerge
        init_on_alloc=1
        init_on_free=1
        page_alloc.shuffle=1
        randomize_kstack_offset=on
        module.sig_enforce=1
        rd.shell=0
        rd.emergency=halt
        lockdown=confidentiality
        vsyscall=none
        ia32_emulation=0
        fb_tunnels=none
        preempt=none
        noautogroup
InitrdProfiles=
KernelInitrdModules=default
Hostname=particle-web-????-????

Packages=
        bash
        ca-certificates
        certbot
        chrony
        coreutils
        dbus-broker
        findutils
        hardened_malloc
        kmod
        nftables
        nginx-core
        no_rlimit_as
        openssh-server
        polkit
        sed
        systemd
        udev
        util-linux

RemoveFiles=
        /usr/bin/arping
        /usr/bin/chage
        /usr/bin/chfn
        /usr/bin/chsh
        /usr/bin/clockdiff
        /usr/bin/gpasswd
        /usr/bin/newgidmap
        /usr/bin/newgrp
        /usr/bin/newuidmap
        /usr/bin/pam_timestamp_check
        /usr/bin/passwd
        /usr/bin/pkexec
        /usr/bin/su

VolatilePackages=
        systemd
        udev

InitrdVolatilePackages=
        systemd
        udev

[Validation]
SecureBoot=yes
SignExpectedPcr=no

[Runtime]
RuntimeSize=12G
RAM=2G
CPUs=2
Ephemeral=yes
