# OBS workers build without network access and provide the shared ParticleOS
# packages through the local /.build.binaries package mirror.
[Match]
PathExists=!/.build.binaries

[Build]
SandboxTrees=mkosi.resources/particleos-obs-pubkey.gpg:/usr/share/pki/rpm-gpg/particleos-obs-pubkey.gpg
             mkosi.resources/particleos-base-obs.repo:/etc/yum.repos.d/particleos-base-obs.repo
             mkosi.resources/particleos-obs.repo:/etc/yum.repos.d/particleos-obs.repo
