# SPDX-License-Identifier: LGPL-2.1-or-later

[Include]
Include=mkosi-initrd

[Output]
Output=initrd

[Content]
Packages=
        btrfs-progs
        dosfstools
        e2fsprogs
        ipe-policy
        less
        libfdisk
        libfido2
        xfsprogs

VolatilePackages=
        systemd
        udev

# NvPCR initialization requires a signed PCR policy and compatible public key.
# This image deliberately uses direct PCR 7 sealing instead.
RemoveFiles=
        /usr/lib/nvpcr
