# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora
Release=44

[Build]
SandboxTrees=%D/mkosi.profiles/obs-repos/systemd.gpg:/usr/share/pki/rpm-gpg/systemd.gpg
             %D/mkosi.profiles/obs-repos/mkosi.conf.d/fedora/mkosi.conf.d/44.repo:/etc/yum.repos.d/systemd.repo
