# SPDX-License-Identifier: LGPL-2.1-or-later

# Empty placeholder. No DNS packages or public service policy are selected.

[Output]
ImageId=ParticleOS-Dnsserver
Output=ParticleOS-Dnsserver_%v_%a

[Content]
UnifiedKernelImageFormat=ParticleOS-Dnsserver_%v_%a
UnifiedKernelImageProfiles=%D/mkosi.profiles/dnsserver/emergency-uki.conf
KernelCommandLine=systemd.image_filter=usr=ParticleOS-Dnsserver_*:usr-verity=ParticleOS-Dnsserver_*:usr-verity-sig=ParticleOS-Dnsserver_*:root=ParticleOS-Dnsserver-*:swap=ParticleOS-Dnsserver-*

Hostname=particle-dns-????-????
