# SPDX-License-Identifier: LGPL-2.1-or-later
# needssslcertforbuild

[Include]
Include=mkosi-obs

[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64
Mirror=https://dl.fedoraproject.org/pub/fedora

[Config]
Profiles=obs-sysupdate

[Build]
ToolsTreeMirror=https://download.opensuse.org

[Output]
SplitArtifacts=
SplitArtifacts=uki,partitions,roothash,os-release,repart-definitions

[Content]
WithDocs=no
WithRecommends=no
Packages=
        authselect
        bash
        ca-certificates
        certbot
        chrony
        coreutils
        dbus-broker
        findutils
        hardened_malloc
        kmod
        nftables
        nginx-core
        no_rlimit_as
        openssh-server
        polkit
        sed
        systemd
        udev
        util-linux
        cryptsetup
        fedora-release
        kernel-core
        pam
        policycoreutils
        procps-ng
        selinux-policy-targeted
        systemd-boot
        systemd-networkd
        systemd-networkd-defaults
        systemd-oomd-defaults
        systemd-pam
        systemd-resolved
        tpm2-tss
        veritysetup

RemoveFiles=
        /usr/bin/arping
        /usr/bin/chage
        /usr/bin/chfn
        /usr/bin/chsh
        /usr/bin/clockdiff
        /usr/bin/gpasswd
        /usr/bin/newgidmap
        /usr/bin/newgrp
        /usr/bin/newuidmap
        /usr/bin/pam_timestamp_check
        /usr/bin/passwd
        /usr/bin/pkexec
        /usr/bin/su

InitrdPackages=
        btrfs-progs
        dosfstools
        e2fsprogs
        ipe-policy
        less
        libfdisk
        libfido2
        selinux-policy-targeted
        xfsprogs
