# SPDX-License-Identifier: LGPL-2.1-or-later

[UKIProfile]
Profile=
        ID=emergency
        TITLE=Emergency Mode

Cmdline=
        root=dissect
        rootflags=nosuid,nodev
        mount.usr=dissect
        systemd.unit=emergency.target
        rw
        audit=1
        audit_backlog_limit=8192
        enforcing=1
        selinux=1
        lockdown=confidentiality
        systemd.verity_usr_options=root-hash-signature=auto
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=absent:=ignore
        systemd.image_filter=usr=ParticleOS-Webserver_*:usr-verity=ParticleOS-Webserver_*:usr-verity-sig=ParticleOS-Webserver_*:root=ParticleOS-Webserver-*:swap=ParticleOS-Webserver-*
        ipe.enforce=1
        slab_nomerge
        init_on_alloc=1
        init_on_free=1
        page_alloc.shuffle=1
        randomize_kstack_offset=on
        module.sig_enforce=1
        rd.shell=0
        rd.emergency=halt
        vsyscall=none
        ia32_emulation=0
        fb_tunnels=none
        noautogroup

SignExpectedPcr=no
