# SPDX-License-Identifier: LGPL-2.1-or-later

[Include]
Include=%D/mkosi.role.conf

[Config]
Dependencies=
Dependencies=base,initrd

[Output]
ImageId=ParticleOS-Webserver
Output=ParticleOS-Webserver_%v_%a

[Content]
BaseTrees=%O/base
CleanPackageMetadata=yes
BuildPackages=
Initrds=%O/initrd
UnifiedKernelImageFormat=ParticleOS-Webserver_%v_%a
UnifiedKernelImageProfiles=%D/mkosi.images/webserver/emergency-uki.conf
KernelCommandLine=systemd.image_filter=usr=ParticleOS-Webserver_*:usr-verity=ParticleOS-Webserver_*:usr-verity-sig=ParticleOS-Webserver_*:root=ParticleOS-Webserver-*:swap=ParticleOS-Webserver-*
Hostname=particle-web-????-????
Packages=
        certbot
        nginx-core
