# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora
Release=44

[Content]
InitrdPackages=
        btrfs-progs
        dosfstools
        e2fsprogs
        ipe-policy
        less
        libfdisk
        libfido2
        selinux-policy-targeted
        xfsprogs

Packages=
        authselect
        cryptsetup
        fedora-release
        kernel-core
        pam
        policycoreutils
        procps-ng
        selinux-policy-targeted
        systemd-boot
        systemd-networkd
        systemd-networkd-defaults
        systemd-oomd-defaults
        systemd-pam
        systemd-resolved
        tpm2-tss
        veritysetup

VolatilePackages=
        systemd-boot
        systemd-networkd
        systemd-networkd-defaults
        systemd-oomd-defaults
        systemd-pam
        systemd-resolved
