# SPDX-License-Identifier: LGPL-2.1-or-later

# Empty placeholder. No DNS packages or public service policy are selected,
# and the aggregate image does not request this image.
[Include]
Include=%D/mkosi.role.conf

[Config]
Dependencies=
Dependencies=base,initrd

[Output]
ImageId=ParticleOS-Dnsserver
Output=ParticleOS-Dnsserver_%v_%a

[Content]
BaseTrees=%O/base
CleanPackageMetadata=yes
BuildPackages=
Initrds=%O/initrd
UnifiedKernelImageFormat=ParticleOS-Dnsserver_%v_%a
UnifiedKernelImageProfiles=
        %D/mkosi.images/dnsserver/emergency-uki.conf
        %D/mkosi.images/dnsserver/install-uki.conf
KernelCommandLine=systemd.image_filter=usr=ParticleOS-Dnsserver_*:usr-verity=ParticleOS-Dnsserver_*:usr-verity-sig=ParticleOS-Dnsserver_*:root=ParticleOS-Dnsserver-*:swap=ParticleOS-Dnsserver-*:home=ParticleOS-Dnsserver-*
Hostname=particle-dns-????-????
Packages=
