# SPDX-License-Identifier: LGPL-2.1-or-later

# Minimal application DDI. It is built from the reviewed custom Stalwart RPM,
# signed by OBS, and mounted directly by PID 1 with RootImage=.
[Output]
ImageId=ParticleOS-Stalwart
ImageVersion=0.16.17.14
Output=ParticleOS-Stalwart_%v_%a
Format=disk
Overlay=no
ManifestFormat=json
SplitArtifacts=partitions,roothash,os-release,repart-definitions
RepartDirectories=%D/mkosi.images/stalwart-service/mkosi.repart
ElTorito=no

[Content]
Bootable=no
Bootloader=none
UnifiedKernelImages=none
CleanPackageMetadata=yes
SELinuxRelabel=yes
WithDocs=no
WithRecommends=no
ExtraTrees=%D/mkosi.images/stalwart-service/mkosi.extra
Packages=
        bash
        ca-certificates
        coreutils
        hardened_malloc
        no_rlimit_as
        policycoreutils
        selinux-policy-targeted
        stalwart
        stalwart-particleos-user
        stalwart-selinux
PostInstallationScripts=%D/mkosi.scripts/stalwart-service.postinst.chroot
FinalizeScripts=%D/mkosi.scripts/stalwart-service.finalize

[Validation]
SecureBoot=no
SignExpectedPcr=no

[Include]
Include=%D/mkosi.service.obs.conf
