# SPDX-License-Identifier: LGPL-2.1-or-later

# Independently published compatible patch DDI.
[Include]
Include=%D/mkosi.images/stalwart-common.conf

[Output]
ImageVersion=0.16.17.26
Output=ParticleOS-Stalwart_%v_%a

[Content]
ExtraTrees=%D/mkosi.images/stalwart-service/mkosi.extra
