# SPDX-License-Identifier: LGPL-2.1-or-later

[Output]
ImageId=ParticleOS-Webserver
Output=ParticleOS-Webserver_%v_%a

[Content]
UnifiedKernelImageFormat=ParticleOS-Webserver_%v_%a
UnifiedKernelImageProfiles=%D/mkosi.profiles/webserver/emergency-uki.conf
KernelCommandLine=systemd.image_filter=usr=ParticleOS-Webserver_*:usr-verity=ParticleOS-Webserver_*:usr-verity-sig=ParticleOS-Webserver_*:root=ParticleOS-Webserver-*:swap=ParticleOS-Webserver-*

Hostname=particle-web-????-????
Packages=
        certbot
        nginx-core
