# SPDX-License-Identifier: LGPL-2.1-or-later
# needssslcertforbuild

[Config]
Dependencies=stalwart-service

[Content]
BuildPackages=
        bash
        ca-certificates
        coreutils
        erofs-utils
        hardened_malloc
        no_rlimit_as
        policycoreutils
        selinux-policy-targeted
        stalwart
        stalwart-particleos-user
        stalwart-selinux
        systemd
        zstd
